# Generated by Django 3.1.3 on 2020-12-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/astro-icon.png', upload_to='images'),
        ),
    ]
