# Generated by Django 3.1.3 on 2020-11-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201129_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='/static/img/dev-icon-small.png', upload_to='users'),
        ),
    ]
